### ISSUE TITLE
Request for RTL support

### ISSUE THREAD

**Issue by bfintal** [glidejs/glide#144]
Would it be possible to add RTL support? Any advice on how to implement this? Thanks :)

**Comment by aTei** [comment]
Can't use it because we have LTR and RTL versions of website and it works only on LTR

**Comment by aTei** [comment]
As partial fix I've added 
```css
.glide {
    direction: ltr;
}
```
so it, at least, works as on LTR

**Comment by aTei** [comment]
Randomly found how to make it work right in RTL
```scss
// it is scss
.glide {
  direction: ltr;

  .glide__slide {
    float: right;
  }
}
```

And just jump to last slide after glide initialized if parent element is rtl
```coffee
    # it is coffeeScript
    isRTL = getComputedStyle($(".glide").parent()[0]).direction == 'rtl'

    if isRTL
      api = glide.data('glide_api')
      api.jump('>>')
```
