### ISSUE TITLE
When using box-shadow, the last slide does not show the full shadow

### ISSUE THREAD

**Issue by opr** [glidejs/glide#528]
Here's a screenshot of it happening and also a link to a code sandbox - any ideas on how to fix this?

![image](https://user-images.githubusercontent.com/5656702/96987061-656e6a00-151a-11eb-9f80-0c61b264676f.png)

https://codesandbox.io/s/purple-https-sp75u?file=/index.html

Thanks!

**Comment by abdennourzahaf** [comment]
Any fix to this?

**Comment by BlackKiwi89** [comment]
help :(

**Comment by demedos** [comment]
The problem is that there is not declarative way to add a padding between the glide container and its slides. A workaround is to take advantage of the `peek` property to add some horizontal margin and some custom css for the top and bottom. 

```ts
/* 
* index.js
* Adjust the peek option as per your needs
*/
new Glide(".glide", {
    peek: 5,
}).mount();
```
```css
/* 
* style.css
* Load this file after the glide stylesheet and adjust the paddings as per your needs
*/
.glide__slides {
    padding-top: 10px;
    padding-bottom: 10px;
}
```
