### ISSUE TITLE
max height for slider container

### ISSUE THREAD

**Issue by Mikilll94** [glidejs/glide#604]
@jedrzejchalubek
Thanks, for this awesome library.

There is one thing which is bugging me. How to set `max-height` for the slider container?

Here is what I am trying:
https://codesandbox.io/s/glidejs-max-height-qo2ek

I have tried to set `max-height: 200px` on .glide-container, .glide, .glide-track, .glide-slides, .glide-slide but nothing is working.

I expect that the images should scale proportionally when the `max-height` is set on glide container.

**Comment by Sammeeey** [comment]
Potential duplicate of #421 (or at least very related).

This [reply here](https://github.com/glidejs/glide/issues/421#issuecomment-554812136) helped me to adjust all images according to the height of `.glide__slides`:
```css
.glide__slides {
    height: 400px;
}

.glide__slide {   /* applies to all images in the slider */
    object-fit: contain;
}
```

According to this [stackoverflow reply](https://stackoverflow.com/a/45736119/12946000) there has been an `autoheight` option in the past.
Doesn't seem to be documented and didn't work for me.
